### ISSUE TITLE
RELEASE SECOND DESIGN

### ISSUE THREAD

**Issue by marvinborner** [lars-ctf/lars-ctf.github.io#1]
HELLO EVERYONE!!

@AnyUnderstanding PLEASE FINALLY PUSH OUR SECOND DESIGN!
IT'S VERY URGENT.

THANKS FOR YOUR ATTENTION!

**Comment by AnyUnderstanding** [comment]
@marvinborner I understand your frustration and appreciate that you're eagerly awaiting the new version of the website. Yet, you have to understand that great design takes great amounts of time. Nevertheless, I want to apologize for the long wait. But the wait has an end, and I'm happy to announce the new version of the website. LIVE NOW 🔴!!!!
